spring:
  application:
    name: rcloud-auth-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
  redis:
    host: ${REDIS_HOST:rich-redis-1.rtongcloud.com}
    port: ${REDIS_PORT:6380}
    pool:
      max-active: 20
  datasource:
    name: sysconfig
    url: jdbc:mysql://${MYSQL_HOST:192.168.108.145}:${MYSQL_PORT:3306}/sysconfig?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: sysconfig
    password: pw4iow16
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 2
    maxWait: 60000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:mapper/*.xml

jwt:
  client-id: rcloud-auth
  expire: 3600
  secret: Wb2!crZFep9fafRDL1C4